#!-*- utf-8 -*-

CheckListHeader_ZH = """
**以下为 openEuler-Advisor 的 review_tool 生成审视要求清单**
如果您是第一次给 openEuler 提交 PR，建议您花一点时间阅读 [Gitee工作流说明](https://gitee.com/openeuler/community/blob/master/zh/contributors/Gitee-workflow.md)

**{go}** 审视者确认符合要求 | **{nogo}** 审视者认为不符合要求 | **{na}** 审视者认为与本PR无关 | **{question}** 审视者无法确认是否符合要求 | **{ongoing}** 审视过程中
**NOTE:** Comment "/review status[go/nogo/na/question/ongoing]:number_list[0,1,2 ...] ..." to update the status.
例如: "/review go:0,1,2 nogo:3,4,5" 或者 "/review go:0-2 nogo:3-5".
如果你想更新所有条目的状态，请评论 "/review status[go/nogo/na/question/ongoing]:999".
|审视项编号|审视类别|审视要求|审视要求说明|审视结果|
|:--:|:--:|:--|:--|:--:|
"""

CheckListHeader_EN = """
**The following table is the PR review checklist generated by the review_tool of openEuler-Advisor.**
If this is the first time that you submit a PR to openEuler, take a few minutes to read [Gitee Workflow](https://gitee.com/openeuler/community/blob/master/zh/contributors/Gitee-workflow.md).

**{go}** The PR meets requirements. | **{nogo}** The PR does not meet requirements. | **{na}** The PR is not applicable. | **{question}** The PR is questionable. | **{ongoing}** The PR is under review.
**NOTE:** Comment "/review status[go/nogo/na/question/ongoing]:number_list[0,1,2 ...] ..." to update the status.
Example: "/review go:0,1,2 nogo:3,4,5" or "/review go:0-2 nogo:3-5".
Comment "/review status[go/nogo/na/question/ongoing]:999" if you want to update the status of all items at a time.
| Item | Category | Requirement | Description | Result |
|:--:|:--:|:--|:--|:--:|
"""

REVIEW_STATUS = {
    'go': '[:white_check_mark:]',
    'nogo': '[&#x1F534;]',
    'na': '[&#x25EF;]',
    'question': '[❓]',
    'ongoing': '[&#x1F535;]'
}

Category_ZH = {
    "PRSubmissionSPEC": "PR提交规范",
    "CleanCode": "Clean Code",
    "OpenSourceCompliance": "开源合规性",
    "SecurityPrivacy": "安全及隐私",
    "Compatibility": "兼容性",
    "PackageSubmission": "制品仓要求",
    "customization": "定制项"
}

Category_EN = {
    "PRSubmissionSPEC": "PR Submission Specifications",
    "CleanCode": "Clean Code",
    "OpenSourceCompliance": "Open Source Compliance",
    "SecurityPrivacy": "Security and Privacy",
    "Compatibility": "Compatibility",
    "PackageSubmission": "Package Submission",
    "customization": "Custom Item"
}

FAILURE_COMMENT = 'Failed to create review list.You can try to rebuild using "/review retrigger".:confused:'
PR_CONFLICT_COMMENT = "Conflict exists in PR.Please resolve conflict before review.@{owner}"

WaitConFirmLabel = "wait_confirm"
